# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Importer
                                 A QGIS plugin
 Importer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-08-08
        copyright            : (C) 2022 by Importer
        email                : Importer
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from qgis.utils import iface
from qgis.PyQt.QtWidgets import QApplication
from qgis.PyQt.QtCore import Qt
from qgis.core import Qgis as QGis
import sys
import os

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Importer class from file Importer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """   
    from .Importer import Importer
    return Importer(iface)
